services:
  - type: web
    name: live-sales-notifications
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: write_products,read_orders
      - key: DATABASE_URL
        fromDatabase:
          name: live-sales-notifications-db
          property: connectionString

databases:
  - name: live-sales-notifications-db
    region: oregon
    plan: free

